## mysql
# UserDataMap
CREATE TABLE DB_TABLE_PREFIXUserDataMap(
 DB_COLUMN_PREFIXuserId int(11) NOT NULL,
 DB_COLUMN_PREFIXfield varchar(128) NOT NULL,
 DB_COLUMN_PREFIXvalue varchar(255),
 INDEX DB_TABLE_PREFIXUserDataMap_69068(DB_COLUMN_PREFIXuserId)
) DB_TABLE_TYPE
/*!40100 DEFAULT CHARACTER SET utf8 */;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('UserDataMap', 1, 0);

## postgres
# UserDataMap
CREATE TABLE DB_TABLE_PREFIXUserDataMap(
 DB_COLUMN_PREFIXuserId INTEGER NOT NULL,
 DB_COLUMN_PREFIXfield VARCHAR(128) NOT NULL,
 DB_COLUMN_PREFIXvalue VARCHAR(255)
);

CREATE INDEX DB_TABLE_PREFIXUserDataMap_69068 ON DB_TABLE_PREFIXUserDataMap(DB_COLUMN_PREFIXuserId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('UserDataMap', 1, 0);

## oracle
# UserDataMap
CREATE TABLE DB_TABLE_PREFIXUserDataMap(
 DB_COLUMN_PREFIXuserId INTEGER NOT NULL,
 DB_COLUMN_PREFIXfield VARCHAR2(128) NOT NULL,
 DB_COLUMN_PREFIXvalue VARCHAR2(255)
);

CREATE INDEX DB_TABLE_PREFIXUserDataMap_69068
   ON DB_TABLE_PREFIXUserDataMap(DB_COLUMN_PREFIXuserId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('UserDataMap', 1, 0);

## db2
# UserDataMap
CREATE TABLE DB_TABLE_PREFIXUserDataMap(
 DB_COLUMN_PREFIXuserId INTEGER NOT NULL,
 DB_COLUMN_PREFIXfield VARCHAR(128) NOT NULL,
 DB_COLUMN_PREFIXvalue VARCHAR(255)
);

CREATE INDEX DB_TABLE_PREFIXUserDbb_69068
   ON DB_TABLE_PREFIXUserDataMap(DB_COLUMN_PREFIXuserId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('UserDataMap', 1, 0);

## mssql
# UserDataMap
CREATE TABLE DB_TABLE_PREFIXUserDataMap(
 DB_COLUMN_PREFIXuserId INT NOT NULL,
 DB_COLUMN_PREFIXfield NVARCHAR(128) NOT NULL,
 DB_COLUMN_PREFIXvalue NVARCHAR(255) NULL
);

CREATE INDEX DB_TABLE_PREFIXUserDataMap_69068 ON DB_TABLE_PREFIXUserDataMap(DB_COLUMN_PREFIXuserId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('UserDataMap', 1, 0);

