## mysql
# UserordersMap
CREATE TABLE DB_TABLE_PREFIXUserordersMap(
 DB_COLUMN_PREFIXitemId int(11) NOT NULL,
 DB_COLUMN_PREFIXitemValue varchar(128),
 PRIMARY KEY(DB_COLUMN_PREFIXitemId)
) DB_TABLE_TYPE
/*!40100 DEFAULT CHARACTER SET utf8 */;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('UserordersMap', 1, 0);

## postgres
# UserordersMap
CREATE TABLE DB_TABLE_PREFIXUserordersMap(
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL,
 DB_COLUMN_PREFIXitemValue VARCHAR(128)
);

ALTER TABLE DB_TABLE_PREFIXUserordersMap ADD PRIMARY KEY (DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('UserordersMap', 1, 0);

## oracle
# UserordersMap
CREATE TABLE DB_TABLE_PREFIXUserordersMap(
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL,
 DB_COLUMN_PREFIXitemValue VARCHAR2(128)
);

ALTER TABLE DB_TABLE_PREFIXUserordersMap
 ADD PRIMARY KEY (DB_COLUMN_PREFIXitemId)
;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('UserordersMap', 1, 0);

## db2
# UserordersMap
CREATE TABLE DB_TABLE_PREFIXUserordersMap(
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL,
 DB_COLUMN_PREFIXitemValue VARCHAR(128)
);

ALTER TABLE DB_TABLE_PREFIXUserordersMap ADD PRIMARY KEY (DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('UserordersMap', 1, 0);

## mssql
# UserordersMap
CREATE TABLE DB_TABLE_PREFIXUserordersMap(
 DB_COLUMN_PREFIXitemId INT NOT NULL,
 DB_COLUMN_PREFIXitemValue NVARCHAR(128) NULL
);

ALTER TABLE DB_TABLE_PREFIXUserordersMap ADD PRIMARY KEY (DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('UserordersMap', 1, 0);

## sqlite
# UserordersMap
CREATE TABLE DB_TABLE_PREFIXUserordersMap(
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL,
 DB_COLUMN_PREFIXitemValue TEXT
);

CREATE UNIQUE INDEX DB_TABLE_PREFIXUserordersMap_pkey ON DB_TABLE_PREFIXUserordersMap(DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('UserordersMap', 1, 0);

