## mysql
# GalleryCheckoutNochexAPC
CREATE TABLE DB_TABLE_PREFIXCheckoutNochexAPC(
 DB_COLUMN_PREFIXid int(11) NOT NULL,
 DB_COLUMN_PREFIXncToEmail varchar(128),
 DB_COLUMN_PREFIXncFromEmail varchar(128),
 DB_COLUMN_PREFIXncTransactionId varchar(128),
 DB_COLUMN_PREFIXncDate varchar(32),
 DB_COLUMN_PREFIXncKey varchar(128),
 DB_COLUMN_PREFIXncAmount varchar(32),
 DB_COLUMN_PREFIXncStatus varchar(32),
 DB_COLUMN_PREFIXnotes text,
 PRIMARY KEY(DB_COLUMN_PREFIXid)
) DB_TABLE_TYPE
/*!40100 DEFAULT CHARACTER SET utf8 */;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutNochexAPC', 1, 0);

## postgres
# GalleryCheckoutNochexAPC
CREATE TABLE DB_TABLE_PREFIXCheckoutNochexAPC(
 DB_COLUMN_PREFIXid INTEGER NOT NULL,
 DB_COLUMN_PREFIXncToEmail VARCHAR(128),
 DB_COLUMN_PREFIXncFromEmail VARCHAR(128),
 DB_COLUMN_PREFIXncTransactionId VARCHAR(128),
 DB_COLUMN_PREFIXncDate VARCHAR(32),
 DB_COLUMN_PREFIXncKey VARCHAR(128),
 DB_COLUMN_PREFIXncAmount VARCHAR(32),
 DB_COLUMN_PREFIXncStatus VARCHAR(32),
 DB_COLUMN_PREFIXnotes text
);

ALTER TABLE DB_TABLE_PREFIXCheckoutNochexAPC ADD PRIMARY KEY (DB_COLUMN_PREFIXid);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutNochexAPC', 1, 0);

## oracle
# GalleryCheckoutNochexAPC
CREATE TABLE DB_TABLE_PREFIXCheckoutNochexAPC(
 DB_COLUMN_PREFIXid INTEGER NOT NULL,
 DB_COLUMN_PREFIXncToEmail VARCHAR2(128),
 DB_COLUMN_PREFIXncFromEmail VARCHAR2(128),
 DB_COLUMN_PREFIXncTransactionId VARCHAR2(128),
 DB_COLUMN_PREFIXncDate VARCHAR2(32),
 DB_COLUMN_PREFIXncKey VARCHAR2(128),
 DB_COLUMN_PREFIXncAmount VARCHAR2(32),
 DB_COLUMN_PREFIXncStatus VARCHAR2(32),
 DB_COLUMN_PREFIXnotes CLOB
);

ALTER TABLE DB_TABLE_PREFIXCheckoutNochexAPC
 ADD PRIMARY KEY (DB_COLUMN_PREFIXid)
;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutNochexAPC', 1, 0);

## db2
# GalleryCheckoutNochexAPC
CREATE TABLE DB_TABLE_PREFIXCheckoutNochexAPC(
 DB_COLUMN_PREFIXid INTEGER NOT NULL,
 DB_COLUMN_PREFIXncToEmail VARCHAR(128),
 DB_COLUMN_PREFIXncFromEmail VARCHAR(128),
 DB_COLUMN_PREFIXncTransactionId VARCHAR(128),
 DB_COLUMN_PREFIXncDate VARCHAR(32),
 DB_COLUMN_PREFIXncKey VARCHAR(128),
 DB_COLUMN_PREFIXncAmount VARCHAR(32),
 DB_COLUMN_PREFIXncStatus VARCHAR(32),
 DB_COLUMN_PREFIXnotes VARCHAR(15000)
);

ALTER TABLE DB_TABLE_PREFIXCheckoutNochexAPC ADD PRIMARY KEY (DB_COLUMN_PREFIXid);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutNochexAPC', 1, 0);

## mssql
# GalleryCheckoutNochexAPC
CREATE TABLE DB_TABLE_PREFIXCheckoutNochexAPC(
 DB_COLUMN_PREFIXid INT NOT NULL,
 DB_COLUMN_PREFIXncToEmail NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXncFromEmail NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXncTransactionId NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXncDate NVARCHAR(32) NULL,
 DB_COLUMN_PREFIXncKey NVARCHAR(128) NULL,
 DB_COLUMN_PREFIXncAmount NVARCHAR(32) NULL,
 DB_COLUMN_PREFIXncStatus NVARCHAR(32) NULL,
 DB_COLUMN_PREFIXnotes NVARCHAR(MAX) NULL
);

ALTER TABLE DB_TABLE_PREFIXCheckoutNochexAPC ADD PRIMARY KEY (DB_COLUMN_PREFIXid);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutNochexAPC', 1, 0);

## sqlite
# GalleryCheckoutNochexAPC
CREATE TABLE DB_TABLE_PREFIXCheckoutNochexAPC(
 DB_COLUMN_PREFIXid INTEGER NOT NULL,
 DB_COLUMN_PREFIXncToEmail TEXT,
 DB_COLUMN_PREFIXncFromEmail TEXT,
 DB_COLUMN_PREFIXncTransactionId TEXT,
 DB_COLUMN_PREFIXncDate TEXT,
 DB_COLUMN_PREFIXncKey TEXT,
 DB_COLUMN_PREFIXncAmount TEXT,
 DB_COLUMN_PREFIXncStatus TEXT,
 DB_COLUMN_PREFIXnotes TEXT
);

CREATE UNIQUE INDEX DB_TABLE_PREFIXCheckoutNochexAPC_pkey ON DB_TABLE_PREFIXCheckoutNochexAPC(DB_COLUMN_PREFIXid);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('CheckoutNochexAPC', 1, 0);

